export const chartOfAccounts = {
  assets: ["Cash on Hand", "Kuwait Bank", "India Bank"],
  liabilities: ["Approved Commitments Payable", "Assistance Payable", "Other Payables"],
  income: ["Member Subscription", "Ramadan Collection", "General Collection", "Bank Interest", "Chitty Income", "Other Income"],
  expenses: [
    "Monthly Food Kit",
    "Monthly Medical Aid",
    "Medical Emergency",
    "Widow Pension",
    "Self Employment Support",
    "Education Assistance",
    "Debt Clearance",
    "House Maintenance Support",
    "Dialysis Assistance",
    "Ramadan Kit",
    "Eid Kit",
    "Social Commitment",
    "Disabled Community Support",
    "Payment Disbursement",
    "Admin Expenses",
  ],
} as const;
